-- 1. 영어학문학과(학과코드 002) 학생들의 학번과 이름, 입학 년도를 입학 년도가
-- 빠른 순으로 표시하는 SQL 문장 작성.
-- (단, 헤더는 "학번", "이름", "입학년도" 표시)
SELECT * FROM TB_STUDENT;

SELECT STUDENT_NO "학번", STUDENT_NAME "이름", ENTRANCE_DATE "입학년도"
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY ENTRANCE_DATE;

-- 2. 춘 기술대학교의 교수 중 이름이 세 글자가 아닌 교수가 한 명 있다.
-- 그 교수의 이름과 주민번호를 화면에 출력.
SELECT * FROM TB_PROFESSOR;

SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) != 3;

-- 3. 춘 기술대학교 남자 교수들의 이름과 나이를 출력.
-- 단, 이때 나이가 적은 사람에서 많은 순서로 화면에 출력.
-- 교수 중 2000년 이후 출생자는 없으며 출력 헤더를 "교수이름", "나이", 나이 계산은 '만'으로 계산.
SELECT * FROM TB_PROFESSOR;

SELECT TO_DATE(SUBSTR(PROFESSOR_SSN, 1, 6), 'RRMMDD') FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN, 8, 1) = '1';
SELECT TO_DATE(SUBSTR(PROFESSOR_SSN, 1, 6), 'YYYY') FROM TB_PROFESSOR;
SELECT TO_DATE(SUBSTR(PROFESSOR_SSN, 1, 6), 'YYYY') FROM TB_PROFESSOR;

SELECT TO_NUMBER(SUBSTR(SYSDATE, 1, 4), 'YYYY') FROM DUAL;

SELECT PROFESSOR_NAME, TRUNC(MONTHS_BETWEEN(SYSDATE, TO_DATE(SUBSTR(PROFESSOR_SSN, 1, 6), 'RRMMDD'))/12) "나이"
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN, 8, 1) = '1'
ORDER BY "나이";

SELECT MIN(PROFESSOR_SSN) FROM TB_PROFESSOR;

SELECT PROFESSOR_NAME "교수 이름", 
TRUNC(MONTHS_BETWEEN(SYSDATE, TO_DATE(SUBSTR(PROFESSOR_SSN, 1, 6), 'RRMMDD'))/12) "나이"
FROM TB_PROFESSOR MAIN
WHERE TRUNC(MONTHS_BETWEEN(SYSDATE, TO_DATE(SUBSTR(PROFESSOR_SSN, 1, 6), 'RRMMDD'))/12)
 = (SELECT MIN(TRUNC(MONTHS_BETWEEN(SYSDATE, TO_DATE(SUBSTR(PROFESSOR_SSN, 1, 6), 'RRMMDD'))/12))
	FROM TB_PROFESSOR SUB
	WHERE SUB.PROFESSOR_SSN = MAIN.PROFESSOR_SSN)
AND SUBSTR(PROFESSOR_SSN, 8, 1) = '1'
ORDER BY "나이";

-- 4. 교수들의 이름 중 성을 제외한 이름만 출력하는 SQL 문장을 작성.
-- 출력 헤더는 "이름"으로 출력.
SELECT * FROM TB_PROFESSOR;
SELECT PROFESSOR_NAME FROM TB_PROFESSOR;

SELECT SUBSTR(PROFESSOR_NAME, 2, 4) "이름" FROM TB_PROFESSOR;

-- 5. 춘 기술대학의 재수생 입학자를 구하려고 한다. 이때, 19살에 입학하면 재수를 하지 않은 것으로 간주.
SELECT * FROM TB_STUDENT;
SELECT TO_DATE(SUBSTR(STUDENT_SSN, 1, 6)) FROM TB_STUDENT;
SELECT ENTRANCE_DATE, TO_DATE(SUBSTR(STUDENT_SSN, 1, 6)) FROM TB_STUDENT;
SELECT STUDENT_NAME, TRUNC(MONTHS_BETWEEN(ENTRANCE_DATE, TO_DATE(SUBSTR(STUDENT_SSN, 1, 6)))/12 + 1) "입학 나이" FROM TB_STUDENT;
SELECT DISTINCT STUDENT_NO, STUDENT_NAME FROM TB_STUDENT
WHERE MONTHS_BETWEEN(ENTRANCE_DATE, TO_DATE(SUBSTR(STUDENT_SSN, 1, 6), 'RRMMDD'))/12 > 19
AND MONTHS_BETWEEN(ENTRANCE_DATE, TO_DATE(SUBSTR(STUDENT_SSN, 1, 6), 'RRMMDD'))/12 <= 20;

-- 6. 2020년 크리스마스는 무슨 요일인가?
SELECT TO_CHAR(TO_DATE('20201225', 'YYYYMMDD'), 'dy') FROM DUAL;

-- 7. 














